def gs_eutran():
    return [
        ("cellReselectionPriority", "SUFFIX"),
        ("qQualMin", "SUFFIX"),
        ("qRxLevMin", "SUFFIX"),
        ("redirectionOrder", "SUFFIX"),  # TODO: Update suffix new baseline
        ("threshHigh", "0"),
        ("threshHigh2", "0"),
    ]


def gs_hsdsch():
    return [
        ("administrativeState", "UNLOCKED"),
        ("codeThresholdPdu656", "0"),
        ("cqiFeedbackCycle", "8"),
        ("deltaAck1", "5"),
        ("deltaAck2", "7"),
        ("deltaCqi1", "4"),
        ("deltaCqi2", "6"),
        ("deltaNack1", "5"),
        ("deltaNack2", "7"),
        ("enhancedL2Support", "ON"),
        ("enhUeDrxSupport", "OFF"),
        ("hsAqmCongCtrlSpiSupport", "1,2,3,4,7"),
        ("hsAqmCongCtrlSupport", "OFF"),
        ("hsFachSupport", "OFF"),
        ("hsMeasurementPowerOffset", "80"),
        ("initialAckNackRepetitionFactor", "1"),
        ("initialCqiRepetitionFactor", "1"),
        ("numHsPdschCodes", "1"),
        ("numHsScchCodes", "4"),
        ("qam64MimoSupport", "OFF"),
        ("qam64Support", "ON"),
    ]


def gs_eul():
    return [
        ("administrativeState", "UNLOCKED"),
        ("edchTti2Support", "ON"),
        ("eulDchBalancingEnabled", "FALSE"),
        ("eulDchBalancingLoad", "32"),
        ("eulDchBalancingOverload", "0"),
        ("eulDchBalancingReportPeriod", "200"),
        ("eulDchBalancingSupport", "OFF"),
        ("eulDchBalancingSuspendDownSw", "OFF"),
        ("eulDchBalancingTimerNg", "1000"),
        ("eulLoadTriggeredSoftCong", "OFF"),
        ("eulMaxTargetRtwp", "-499"),
        ("eulTdSchedulingSupport", "OFF"),
        ("improvedL2Support", "OFF"),
        ("numEagchCodes", "1"),
        ("numEhichErgchCodes", "2"),
        ("pathlossThresholdEulTti2", "170"),
        ("releaseAseUlNg", "3"),
        ("threshEulTti2Ecno", "-24"),
    ]


def gs_pch():
    return [
        ("administrativeState", "UNLOCKED"),
        ("pchPower", "-4"),
        ("pichPower", "-7"),
        ("sccpchOffset", "20"),
    ]


def gs_fach():
    return [
        ("administrativeState", "UNLOCKED"),
        ("maxFach1Power", "18"),
        ("maxFach2Power", "15"),
        ("pOffset1Fach", "0"),
        ("pOffset3Fach", "0"),
        ("sccpchOffset", "0"),
    ]


def gs_rach():
    return [
        ("administrativeState", "UNLOCKED"),
        ("aichPower", "-6"),
        ("aichTransmissionTiming", "4"),
        ("constantValueCprach", "-27"),
        ("maxPreambleCycle", "4"),
        ("nb01Max", "0"),
        ("nb01Min", "0"),
        ("powerOffsetP0", "1"),
        ("powerOffsetPpm", "-4"),
        ("preambleRetransMax", "32"),
        ("preambleSignatures", "65535"),
        ("scramblingCodeWordNo", "0"),
        ("spreadingFactor", "64"),
        ("subChannelNo", "4095"),
    ]


# INFO: update
def gs_utrancell():
    return [
        ("absPrioCellRes_sPrioritySearch1", "16"),
        ("absPrioCellRes_measIndFach", "DISABLED"),
        ("absPrioCellRes_sPrioritySearch2", "0"),
        ("absPrioCellRes_threshServingLow", "16"),
        ("absPrioCellRes_cellReselectionPriority", "1"),
        ("accessClassesBarredCs0", "FALSE"),
        ("accessClassesBarredCs1", "FALSE"),
        ("accessClassesBarredCs2", "FALSE"),
        ("accessClassesBarredCs3", "FALSE"),
        ("accessClassesBarredCs4", "FALSE"),
        ("accessClassesBarredCs5", "FALSE"),
        ("accessClassesBarredCs6", "FALSE"),
        ("accessClassesBarredCs7", "FALSE"),
        ("accessClassesBarredCs8", "FALSE"),
        ("accessClassesBarredCs9", "FALSE"),
        ("accessClassesBarredCs10", "FALSE"),
        ("accessClassesBarredCs11", "FALSE"),
        ("accessClassesBarredCs12", "FALSE"),
        ("accessClassesBarredCs13", "FALSE"),
        ("accessClassesBarredCs14", "FALSE"),
        ("accessClassesBarredCs15", "FALSE"),
        ("accessClassesBarredPs0", "FALSE"),
        ("accessClassesBarredPs1", "FALSE"),
        ("accessClassesBarredPs2", "FALSE"),
        ("accessClassesBarredPs3", "FALSE"),
        ("accessClassesBarredPs4", "FALSE"),
        ("accessClassesBarredPs5", "FALSE"),
        ("accessClassesBarredPs6", "FALSE"),
        ("accessClassesBarredPs7", "FALSE"),
        ("accessClassesBarredPs8", "FALSE"),
        ("accessClassesBarredPs9", "FALSE"),
        ("accessClassesBarredPs10", "FALSE"),
        ("accessClassesBarredPs11", "FALSE"),
        ("accessClassesBarredPs12", "FALSE"),
        ("accessClassesBarredPs13", "FALSE"),
        ("accessClassesBarredPs14", "FALSE"),
        ("accessClassesBarredPs15", "FALSE"),
        ("accessClassNBarred0", "FALSE"),
        ("accessClassNBarred1", "FALSE"),
        ("accessClassNBarred2", "FALSE"),
        ("accessClassNBarred3", "FALSE"),
        ("accessClassNBarred4", "FALSE"),
        ("accessClassNBarred5", "FALSE"),
        ("accessClassNBarred6", "FALSE"),
        ("accessClassNBarred7", "FALSE"),
        ("accessClassNBarred8", "FALSE"),
        ("accessClassNBarred9", "FALSE"),
        ("accessClassNBarred10", "FALSE"),
        ("accessClassNBarred11", "FALSE"),
        ("accessClassNBarred12", "FALSE"),
        ("accessClassNBarred13", "FALSE"),
        ("accessClassNBarred14", "FALSE"),
        ("accessClassNBarred15", "FALSE"),
        ("admBlockRedirection_gsmRrc", "OFF"),
        ("admBlockRedirection_speech", "OFF"),
        ("admBlockRedirection_rrc", "ON"),
        ("administrativeState", "UNLOCKED"),
        ("amrNbSelector", "MULTI_RATE"),
        ("amrWbRateDlMax", "12650"),
        ("amrWbRateUlMax", "12650"),
        ("anrIafUtranCellConfig_sib11IafAnclEnabled", "FALSE"),
        ("anrIafUtranCellConfig_relationRemoveEnabled", "TRUE"),
        ("anrIafUtranCellConfig_relationAddEnabled", "TRUE"),
        ("anrIafUtranCellConfig_anrEnabled", "TRUE"),
        ("anrIefUtranCellConfig_anrEnabled", "TRUE"),
        ("anrIefUtranCellConfig_sib11IefAnclEnabled", "TRUE"),
        ("aseDlAdm", "500"),
        ("aseLoadThresholdUlSpeech_amr12200", "100"),
        ("aseLoadThresholdUlSpeech_amrWb8850", "100"),
        ("aseLoadThresholdUlSpeech_amr5900", "100"),
        ("aseLoadThresholdUlSpeech_amr7950", "100"),
        ("aseLoadThresholdUlSpeech_amrWb12650", "100"),
        ("aseUlAdm", "500"),
        ("autoAcbEnabled", "FALSE"),
        ("autoAcbMaxPsClassesToBar", "10"),
        ("autoAcbMinRcssrInput", "5"),
        ("autoAcbRcssrThresh", "50"),
        ("autoAcbRcssrWeight", "2"),
        ("autoAcbRtwpThresh", "-70"),
        ("autoAcbRtwpWeight", "10"),
        ("bchPower", "-31"),
        ("cellReserved", "NOT_RESERVED"),
        ("codeLoadThresholdDlSf128", "10"),
        ("compModeAdm", "15"),
        ("ctchAdmMargin", "0"),
        ("ctchOccasionPeriod", "255"),
        ("dchIflsMarginCode", "0"),
        ("dchIflsMarginPower", "0"),
        ("dchIflsThreshCode", "0"),
        ("dchIflsThreshPower", "0"),
        ("dlCodeAdm", "95"),
        ("dlCodeOffloadLimit", "100"),
        ("dlCodePowerCmEnabled", "FALSE"),
        ("dlPowerOffloadLimit", "100"),
        ("dmcrEnabled", "TRUE"),
        ("dnclEnabled", "FALSE"),
        ("eulNonServingCellUsersAdm", "100"),
        ("eulServingCellUsersAdm", "64"),
        ("eulServingCellUsersAdmTti2", "1"),
        ("fachMeasOccaCycLenCoeff", "0"),
        ("ganHoEnabled", "FALSE"),
        ("hardIfhoCorr", "3"),
        ("hcsSib3Config_sSearchHcs", "-105"),
        ("hcsSib3Config_hcsPrio", "0"),
        ("hcsSib3Config_qHcs", "0"),
        ("hcsUsage_idleMode", "FALSE"),
        ("hcsUsage_connectedMode", "FALSE"),
        ("hsdpaUsersAdm", "85"),
        ("hsdpaUsersOffloadLimit", "100"),
        ("hsIflsDownswitchTrigg_toFach", "OFF"),
        ("hsIflsDownswitchTrigg_fastDormancy", "OFF"),
        ("hsIflsDownswitchTrigg_toUra", "OFF"),
        ("hsIflsHighLoadThresh", "100"),
        ("hsIflsMarginUsers", "0"),
        ("hsIflsSpeechMultiRabTrigg", "OFF"),
        ("hsIflsThreshUsers", "0"),
        ("hsIflsTrigger_fromUra", "ON"),
        ("hsIflsTrigger_fromFach", "ON"),
        ("iFCong", "621"),
        ("iFHyst", "6000"),
        ("iflsCpichEcnoThresh", "-24"),
        ("iflsMode", "RAB_EST"),
        ("inactivityTimerEnhUeDrx", "-1"),
        ("individualOffset", "0"),
        ("interFreqFddMeasIndicator", "FALSE"),
        ("interPwrMax", "38"),
        ("interRate", "7760"),
        ("loadBasedHoSupport", "FALSE"),
        ("loadSharingGsmFraction", "100"),
        ("loadSharingGsmThreshold", "90"),
        ("loadSharingMargin", "SUFFIX"),
        ("maximumTransmissionPower", "478"),
        ("maxPwrMax", "48"),
        ("maxRate", "40690"),
        ("maxTxPowerUl", "24"),
        ("minimumRate", "1590"),
        ("minPwrMax", "20"),
        ("minPwrRl", "-150"),
        ("nOutSyncInd", "10"),
        ("pathlossThreshold", "170"),
        ("primarySchPower", "-18"),
        ("primaryTpsCell", "FALSE"),
        ("pwrAdm", "95"),
        ("pwrLoadThresholdDlSpeech_amr12200", "100"),
        ("pwrLoadThresholdDlSpeech_amrWb8850", "100"),
        ("pwrLoadThresholdDlSpeech_amr5900", "100"),
        ("pwrLoadThresholdDlSpeech_amr7950", "100"),
        ("pwrLoadThresholdDlSpeech_amrWb12650", "100"),
        ("qHyst1", "SUFFIX"),
        ("qHyst2", "4"),
        ("qQualMin", "-24"),
        ("qRxLevMin", "SUFFIX"),
        ("qualMeasQuantity", "SUFFIX"),
        ("rateSelectionPsInteractive_dlPrefRate", "16"),
        ("rateSelectionPsInteractive_channelType", "DCH"),
        ("rateSelectionPsInteractive_ulPrefRate", "16"),
        ("releaseRedirect", "EUTRA"),
        ("releaseRedirectEutraTriggers_dchToFach", "ON"),
        ("releaseRedirectEutraTriggers_csFallbackDchToFach", "ON"),
        ("releaseRedirectEutraTriggers_fachToUra", "ON"),
        ("releaseRedirectEutraTriggers_fastDormancy", "OFF"),
        ("releaseRedirectEutraTriggers_csFallbackCsRelease", "ON"),
        ("releaseRedirectEutraTriggers_normalRelease", "ON"),
        ("releaseRedirectHsIfls", "OFF"),
        ("reportingRange1a", "6"),  # TODO: need confirm
        ("reportingRange1b", "14"),  # TODO: need confirm
        ("rlFailureT", "10"),
        ("rrcLcEnabled", "TRUE"),
        ("rwrEutraCc", "OFF"),
        ("secondaryCpichPower", "0"),
        ("secondarySchPower", "-35"),
        ("servDiffRrcAdmHighPrioProfile", "ALL"),
        ("sf128Adm", "10"),
        ("sf16Adm", "0"),
        ("sf16AdmUl", "10"),
        ("sf16gAdm", "0"),
        ("sf32Adm", "10"),
        ("sf4AdmUl", "0"),
        ("sf64AdmUl", "100"),
        ("sf8Adm", "0"),
        ("sf8AdmUl", "0"),
        ("sf8gAdmUl", "0"),
        ("sHcsRat", "-105"),
        ("sInterSearch", "SUFFIX"),
        ("sIntraSearch", "0"),
        ("sRatSearch", "0"),
        ("standAloneSrbSelector", "SRB136"),
        ("timeToTrigger1a", "7"),  # TODO: Need confirm
        ("timeToTrigger1b", "12"),  # TODO: Need Confirm
        ("transmissionScheme", "SINGLE_ANTENNA"),
        ("treSelection", "1"),
        ("usedFreqThresh2dEcno", "SUFFIX"),
        ("usedFreqThresh2dRscp", "SUFFIX"),
    ]


# INFO: Adding
def gs_externalgsmcell():
    return [
        ("bandIndicator", "OTHER_BANDS"),
        ("individualOffset", "0"),
        ("maxTxPowerUl", "24"),
        ("qRxLevMin", "-115"),
    ]


def gs_gsmrelation():
    return [
        ("mobilityRelationType", "HO_AND_CELL_RESEL"),
        ("qOffset1sn", "50"),
    ]


def gs_iublink():
    return [
        ("administrativeState", "UNLOCKED"),
        ("controlPlaneTransportOption_ipv4", "TRUE"),
        ("controlPlaneTransportOption_atm", "FALSE"),
        ("dlHwAdm", "92"),
        ("l2EstReqRetryTimeNbapC", "5"),
        ("l2EstReqRetryTimeNbapD", "5"),
        ("ulHwAdm", "92"),
        ("userPlaneTransportOption_ipv4", "TRUE"),
        ("userPlaneTransportOption_atm", "FALSE"),
    ]


def gs_license():
    return [
        ("CXC4011018", "ACTIVATED"),
        ("CXC4011823", "ACTIVATED"),
        ("CXC4012016", "ACTIVATED"),
        ("CXC4020001", "ACTIVATED"),
        ("CXC4020002", "ACTIVATED"),
        ("CXC4020003", "ACTIVATED"),
        ("CXC4020005", "ACTIVATED"),
        ("CXC4020005", "ACTIVATED"),
        ("CXC4020008", "ACTIVATED"),
        ("CXC4020010", "ACTIVATED"),
        ("CXC4020011", "ACTIVATED"),
        ("CXC4020013", "ACTIVATED"),
        ("CXC4020014", "ACTIVATED"),
        ("CXC4020016", "ACTIVATED"),
        ("CXC4020022", "ACTIVATED"),
        ("CXC4020025", "ACTIVATED"),
        ("CXC4020030", "ACTIVATED"),
        ("CXC4020031", "ACTIVATED"),
        ("CXC4020040", "ACTIVATED"),
        ("CXC4020042", "ACTIVATED"),
        ("CXC4020051", "ACTIVATED"),
        ("CXC4020075", "ACTIVATED"),
        ("CXC4020102", "ACTIVATED"),
        ("CXC4020103", "ACTIVATED"),
        ("CXC4040009", "ACTIVATED"),
    ]


def gs_nodebfunction():
    return [
        ("eul2msFirstSchedStep", "20"),
        ("eulLowRate", "32"),
        ("eulMaxAllowedSchRate", "5376"),
        ("eulMaxShoRate", "5760"),
        ("eulNonServHwRate", "128"),
        ("eulNoReschUsers", "5"),
        ("eulTargetRate", "128"),
    ]


def gs_nodebsectorcarrier():
    return [
        ("eulMaxOwnUuLoad", "80"),
        ("eulMaxRotCoverage", "300"),
        ("eulNoiseFloorLock", "-1040"),
        ("eulThermalLevelPrior", "-1040"),
    ]


def gs_nodeblocalcell():
    return [
        ("airRateTypeSelector", "TRANSMITTED"),
        ("cqiAdjustmentOn", "true"),
        ("cqiErrors", "10"),
        ("cqiErrorsAbsent", "10"),
        ("featCtrlEnhancedLayer2", "ON"),
        ("featCtrlHsdpaDynamicCodeAllocation", "ON"),
        ("featCtrlHsdpaIncrementalRedundancy", "ON"),
        ("featCtrlHsdpaMc", "OFF"),
        ("featCtrlHsdpaMcInactCtrl", "OFF"),
        ("hsPowerMargin", "0"),
        ("hsScchMaxCodePower", "-10"),
        ("hsScchMinCodePower", "-150"),
        ("maxEAgchPowerDl", "-183"),
        ("maxEAgchPowerDlTti2", "-123"),
        ("maxNumEulUsers", "96"),
        ("maxNumHsdpaUsers", "96"),
        ("maxNumHsPdschCodes", "15"),
        ("maxUserEHichERgchPowerDl", "-183"),
        ("qualityCheckPower", "0"),
        ("queueSelectAlgorithm", "PROPORTIONAL_FAIR_MEDIUM"),
        ("schCongPeriodGbr", "5"),
        ("schCongThreshGbr", "5"),
        ("schCongThreshNonGbr", "2"),
        ("schMinPowerNonGbrHsUsers", "0"),
        ("schNoCongPeriodGbr", "5"),
        ("schNoCongThreshGbr", "15"),
        ("schPowerDeltaCongGbr", "50"),
        ("schPrioForAbsResSharing", "15"),
        ("administrativeState", "UNLOCKED"),
    ]
